import { app, shell, BrowserWindow, ipcMain, protocol, net } from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import { autoUpdater } from 'electron-updater'
import icon from '../../resources/icon.png?asset'
import { listScanners, scanPage } from './scanner'
import fs from 'fs'
import path from 'path'

// Register scheme as privileged to allow fetching resources
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'scan',
    privileges: { bypassCSP: true, secure: true, supportFetchAPI: true, standard: true }
  }
])

// Auto-updater configuration
let mainWindow: BrowserWindow | null = null

function setupAutoUpdater(): void {
  // Don't check for updates in development
  if (is.dev) {
    console.log('Auto-updater disabled in development mode')
    return
  }

  // Configure auto-updater
  autoUpdater.autoDownload = false // Don't auto-download, let user decide
  autoUpdater.autoInstallOnAppQuit = true

  // Event handlers
  autoUpdater.on('checking-for-update', () => {
    console.log('Checking for updates...')
    mainWindow?.webContents.send('update-checking')
  })

  autoUpdater.on('update-available', (info) => {
    console.log('Update available:', info.version)
    mainWindow?.webContents.send('update-available', info)
  })

  autoUpdater.on('update-not-available', () => {
    console.log('No updates available')
    mainWindow?.webContents.send('update-not-available')
  })

  autoUpdater.on('download-progress', (progress) => {
    console.log(`Download progress: ${progress.percent}%`)
    mainWindow?.webContents.send('update-download-progress', progress)
  })

  autoUpdater.on('update-downloaded', (info) => {
    console.log('Update downloaded:', info.version)
    mainWindow?.webContents.send('update-downloaded', info)
  })

  autoUpdater.on('error', (error) => {
    console.error('Auto-updater error:', error)
    mainWindow?.webContents.send('update-error', error.message)
  })

  // Check for updates on startup (after a delay to let the app initialize)
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      console.error('Failed to check for updates:', err)
    })
  }, 3000)

  // Check for updates every hour
  setInterval(
    () => {
      autoUpdater.checkForUpdates().catch((err) => {
        console.error('Failed to check for updates:', err)
      })
    },
    60 * 60 * 1000
  ) // 1 hour
}

function createWindow(): void {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    minWidth: 600,
    minHeight: 600,
    show: false,
    autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false
    }
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow?.show()
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  // HMR for renderer base on electron-vite cli.
  // Load the remote URL for development or the local html file for production.
  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // Set app user model id for windows
  electronApp.setAppUserModelId('com.electron')

  // Default open or close DevTools by F12 in development
  // and ignore CommandOrControl + R in production.
  // see https://github.com/alex8088/electron-toolkit/tree/master/packages/utils
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })

  // IPC test
  ipcMain.on('ping', () => console.log('pong'))

  // Custom protocol for serving scanned images from temp directory
  protocol.handle('scan', (request) => {
    const url = request.url.replace('scan://', '')
    // Decode URL to handle spaces/special chars in Windows paths if any (though temp usually simple)
    const filePath = decodeURIComponent(url)
    // Security check: ensure it's inside temp folder?
    // For now, we trust the paths generated by our own scanPage function.
    return net.fetch(`file:///${filePath}`)
  })

  ipcMain.handle('get-scanners', async () => {
    try {
      return await listScanners()
    } catch (error) {
      console.error('Failed to list scanners:', error)
      return []
    }
  })

  ipcMain.handle('scan-page', async (_, deviceId) => {
    try {
      const filePath = await scanPage(deviceId)
      return {
        success: true,
        path: filePath,
        image: `scan://${filePath}`
      }
    } catch (e) {
      console.error('Scan failed:', e)
      const errorMessage = e instanceof Error ? e.message : String(e)
      return { success: false, error: errorMessage }
    }
  })

  ipcMain.handle('cleanup-session', async () => {
    try {
      const tempDir = path.join(app.getPath('temp'), 'SimplyScan')
      if (fs.existsSync(tempDir)) {
        await fs.promises.rm(tempDir, { recursive: true, force: true })
        await fs.promises.mkdir(tempDir, { recursive: true })
      }
      return { success: true }
    } catch (e) {
      console.error('Cleanup failed:', e)
      return { success: false }
    }
  })

  // Auto-updater IPC handlers
  ipcMain.handle('check-for-updates', async () => {
    if (is.dev) {
      return { available: false, message: 'Updates disabled in development' }
    }
    try {
      const result = await autoUpdater.checkForUpdates()
      return { available: true, info: result?.updateInfo }
    } catch (error) {
      console.error('Check for updates failed:', error)
      return { available: false, error: error instanceof Error ? error.message : 'Unknown error' }
    }
  })

  ipcMain.handle('download-update', async () => {
    if (is.dev) {
      return { success: false, message: 'Updates disabled in development' }
    }
    try {
      await autoUpdater.downloadUpdate()
      return { success: true }
    } catch (error) {
      console.error('Download update failed:', error)
      return { success: false, error: error instanceof Error ? error.message : 'Unknown error' }
    }
  })

  ipcMain.handle('install-update', () => {
    if (is.dev) {
      return
    }
    autoUpdater.quitAndInstall(false, true)
  })

  createWindow()

  // Setup auto-updater after window is created
  setupAutoUpdater()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
